name: fitwith
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
  crypto:
  shared_preferences:
  jwt_decoder: ^1.0.3
  image_picker:
  google_maps_flutter:

  # following page : https://pub.dev/packages/provider
  provider: ^4.3.2+3

  # following page : https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.0

  # following page : https://pub.dev/packages/flutter_swiper
  flutter_swiper: ^1.1.6

  # following page : https://pub.dev/packages/keyboard_visibility
  keyboard_visibility: ^0.5.6

  # following page : https://pub.dev/packages/multi_charts
  multi_charts: ^0.2.0

  # following page : https://pub.dev/packages/percent_indicator
  percent_indicator: ^2.1.9

  # following page : https://pub.dev/packages/intl
  intl: ^0.16.1

  # following page : https://pub.dev/packages/table_calendar
  table_calendar: ^2.3.3

  mime_type: ^0.3.2

  http_parser: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: fonts/SpoqaHanSansNeo-Thin.ttf
          weight: 100
        - asset: fonts/SpoqaHanSansNeo-Light.ttf
          weight: 300
        - asset: fonts/SpoqaHanSansNeo-Regular.ttf
          weight: 400
        - asset: fonts/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: fonts/SpoqaHanSansNeo-Bold.ttf
          weight: 700